FROM node:latest

ENV DB_HOST=nwdb DB_PORT=3306 \
    DB_USER=root DB_PASSWORD=changeit \
    APP_PORT=5200 APP_DIR=/app

WORKDIR ${APP_DIR}

ADD main.js .
ADD package.json .
ADD config config
ADD public public
ADD views views

RUN npm install

# Defines how image is executed
EXPOSE ${APP_PORT}

HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 \
    CMD curl -f -s http://localhost:${APP_PORT}/health || exit 1

ENTRYPOINT [ "node", "main.js" ]