apiVersion: v1
kind: Pod

metadata:
  name: fortune-pod
  namespace: default
  labels:
    app.kubernetes.io/name: fortune-pod
    app.kubernetes.io/version: "v1"
    owner: SaiKangWarriors

spec:
  containers: 
  - name: fortune 
    image: digitalkurve/fortune:v1
    imagePullPolicy: Always
    env: 
    - name: APP_PORT
      value: "3000"
    ports: 
    - name: fortune-port
      containerPort: 3000
